// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuYa5IS8OAtvPhFIyJM-7Q6vJP4SuywhY',
    appId: '1:468331091523:web:f1fb6103165e77c79d26f6',
    messagingSenderId: '468331091523',
    projectId: 'project-manager-app-dev',
    authDomain: 'project-manager-app-dev.firebaseapp.com',
    storageBucket: 'project-manager-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdow6Pn9RJ7Py3A5bKgL8gcNfgNZ4_W-I',
    appId: '1:468331091523:android:c67ab120c3e0cc0b9d26f6',
    messagingSenderId: '468331091523',
    projectId: 'project-manager-app-dev',
    storageBucket: 'project-manager-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaBd16e2xsWCZ1NT7r5-SBOArUMfXllYM',
    appId: '1:468331091523:ios:4e0a05ba8dc099289d26f6',
    messagingSenderId: '468331091523',
    projectId: 'project-manager-app-dev',
    storageBucket: 'project-manager-app-dev.firebasestorage.app',
    iosBundleId: 'com.example.projectManagerApp',
  );
}
